### PR TITLE
Add the DFGM service

### PR DESCRIPTION
**Pull request by DanielSacro**

### CODE REVIEW

**Comment by Taylorr82** [comment]
There's something very wrong with the history of this branch. It should not be changing 595 files. I see the Debug folder has a lot of stuff in it. Also, this many conflicts is a big red flag. How outdated is the branching point of this branch?

**Comment by DanielSacro** [comment]
> There's something very wrong with the history of this branch. It should not be changing 595 files. I see the Debug folder has a lot of stuff in it. Also, this many conflicts is a big red flag. How outdated is the branching point of this branch?

I believe it was branched out from master 2 months ago, which seems pretty outdated. How should I go about fixing all the conflicts?

**Comment by joshdellaz** [comment]
I think you'll have to rebase with the current master before the PR

**Review by Taylorr82 — CHANGES_REQUESTED** [review]

**Comment by DanielSacro** [comment]
Alright I'll try that out. Since I'm going to be making a new branch off master, should this pull request also be closed/deleted along with the dfgm_service branch? And should I make a new pull request with the new branch once that's ready?

**Comment by Taylorr82** [comment]
Just delete this one and make a new branch/pr yeah.

**Pull request closed without merging**
