### PR TITLE
Declare sys_log with enum type instead of int

### PR DESCRIPTION
**Pull request by Taylorr82**

### CODE REVIEW

**Review by rcunrau — APPROVED** [review]
Sorry, I had envisioned we'd be doing filtering etc based on integer level comparison

**Comment by Taylorr82** [comment]
> Sorry, I had envisioned we'd be doing filtering etc based on integer level comparison

Would you consider that still possible? I just wanted it to be more obvious to programmers that the meanings are in an enum

**Comment by rcunrau** [comment]
We're definitely going to be doing run-time filtering (is Patrick already
working on it?). I think this way is more correct, the casts for the
filtering will be internal anyway.

**Comment by Taylorr82** [comment]
I think a bitmask is the way to go with filtering, so I think I should redeclare the enum with bitshifts to allow masking. Do you agree?

**Comment by Taylorr82** [comment]
I like the way you did it before better. Makes more sense than disabling certain levels individually to me

**Pull request merged**
