### PR TITLE
Add instantaneous HK subservice

### PR DESCRIPTION
**Pull request by Taylorr82**

### CODE REVIEW

**Review by rcunrau — COMMENTED** [review]
Kinda confused here - does this code not already exist somewhere? Is it different because we normally read HK data from the SD card? And I thought there was a recent refactor/cleanup where we replaced all the little memcpy() calls with a single copy-the-whole-thing call?

**Comment by Taylorr82** [comment]
> Kinda confused here - does this code not already exist somewhere? Is it different because we normally read HK data from the SD card? And I thought there was a recent refactor/cleanup where we replaced all the little memcpy() calls with a single copy-the-whole-thing call?
> 

The subservice only gets from preexisting files, I realized that today. 

And the optimization we did was get rid of all the little red_write() calls. I do agree the memcpys should be reduced (even if just to avoid the duplicated code I made here) but that required a bigger audit of HK that I'm working on right now

**Review by rcunrau — DISMISSED** [review]

**Review by rcunrau — APPROVED** [review]
:-)

**Comment by rcunrau** [comment]
I wondered if it made sense to use the code that writes it to a file,
except write it to a packet instead.

**Pull request merged**
